/**
 * Shared type definitions for MVP / any national-team variant.
 *
 * To add a new country:
 *   1. Run the scraper for that country → produces a JSON dataset
 *   2. Create `src/config/<country>.ts` implementing TeamConfig
 *   3. Point App.tsx at the new config
 *   No other code changes needed.
 */

/** Color palette for a team. All UI colors are sourced from here. */
export interface TeamColors {
  /** Primary brand color — used for borders, active states (e.g. shirt base color). */
  primary: string;
  /** Secondary brand color — title, countdown, highlights (e.g. jersey accent). */
  secondary: string;
  /** Accent color — reserved for future use (e.g. third kit color). */
  accent: string;
  /** Page background color. */
  background: string;
  /** Card / panel / input background color. */
  surface: string;
  /** Primary text color. */
  text: string;
  /** Subdued text — labels, hints, muted info. */
  textMuted: string;

  // ── Cell result colors ─────────────────────────────────────────────────────
  /** Exact match — attribute is correct. */
  correct: string;
  /** Near miss — attribute is within the close range. */
  close: string;
  /** Wrong / too far — attribute is outside the close range. */
  wrong: string;
}

/** Per-team configuration. One file per country, zero code changes elsewhere. */
export interface TeamConfig {
  /** Unique identifier — used as the AsyncStorage namespace key. */
  id: string;
  /** Display name shown in the header (e.g. "MVP"). */
  title: string;
  /** Flag emoji for the team (e.g. "🇧🇷"). */
  flag: string;
  /**
   * Optional locale override for i18n.
   * Falls back to browser/device language if omitted.
   * Supported values: 'pt' | 'en'
   */
  locale?: string;
  /**
   * The player dataset loaded via require().
   * Shape: Player[]  (see below)
   * Generated by the scraper in /backend.
   */
  datasetPath: Player[];
  /** Team color palette. */
  colors: TeamColors;
}

/**
 * A single national team player record.
 * Produced by the scraper and stored in src/data/<country>_players.json.
 *
 * All stats are frozen at scrape time.
 * Re-run the scraper to update active players.
 */
export interface Player {
  /** Full name as it appears on Wikipedia (UTF-8, accents preserved). */
  name: string;
  /** Generalised position: GK | DEF | MID | FWD */
  position: 'GK' | 'DEF' | 'MID' | 'FWD';
  /** Total international appearances (caps). Minimum 10 to be in the pool. */
  caps: number;
  /** International goals only. */
  goals: number;
  /** Year of first international cap (YYYY). */
  first_year: number;
  /** Year of most recent international cap (YYYY). */
  last_year: number;
  /**
   * Optional fun fact shown on the End Screen.
   * Leave empty string ("") until a reliable source is found.
   * Will be populated manually or via a future data source.
   */
  fun_fact: string;
}
